name: CI

on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - run: git remote add azure https://wongchunyat:${{secrets.AZURE_TOKEN}}@dev.azure.com/wongchunyat/wcyat.me/_git/static.wcyat.me
      - run: git pull --ff-only azure master && git push origin master && git push azure master
